export { default as is } from './is';
export { default as to } from './to';
export { default as sym } from './sym';
export { default as map } from './map';
export { default as join } from './join';
export { default as split } from './split';
export { default as has, funcHas, objHas } from './has';
export { default as init } from './init';
export { default as sugar } from './sugar';
export { default as err } from './err';
export { default as asrt } from './asrt';
